Growith-1-1/Backend

- src/main/java/dev/book/challenge/challenge_invite/entity/ChallengeInvite.java
- src/main/java/dev/book/challenge/challenge_invite/repository/ChallengeInviteRepository.java
- src/main/java/dev/book/challenge/controller/ChallengeController.java
- src/main/java/dev/book/challenge/controller/ChallengeInviteController.java
- src/main/java/dev/book/challenge/dto/request/ChallengeInviteRequest.java
- src/main/java/dev/book/challenge/dto/response/ChallengeInviteResponse.java
- src/main/java/dev/book/challenge/entity/Challenge.java
- src/main/java/dev/book/challenge/exception/ErrorCode.java
- src/main/java/dev/book/challenge/service/ChallengeInviteService.java
- src/main/java/dev/book/challenge/service/ChallengeService.java
- src/main/java/dev/book/challenge/user_challenge/entity/UserChallenge.java
- src/main/java/dev/book/challenge/user_challenge/repository/UserChallengeRepository.java
- src/main/java/dev/book/user_challenge/repository/UserChallengeRepository.java
- src/test/java/dev/book/challenge/service/ChallengeInviteServiceTest.java
- src/test/java/dev/book/challenge/service/ChallengeServiceTest.java
챌린지 참가 및 초대 기능을 추가
Resolves: #5 
어떤 변경 사항이 있나요?
- 챌린지만 속한 사람만 초대 할 수 있도록 구현 하였습니다
- 중복 초대를 못하도록 구현하였습니다.
- 최대 인원을 넘으면 초대와 참여를 못하도록 구현하였습니다.
- 나한테 온 초대목록을 조회 할 수 있도록 구현하였습니다
- 초대에 대한 수락 및 거절을 추가하였습니다.
- 계속해서 테스트를 추가하겠습니다.
> [Feature] 챌린지 참가 및 초대 기능 추가 #5

- src/main/java/dev/book/global/config/security/SecurityConfig.java
- src/main/java/dev/book/global/config/security/dto/PermitUrlProperties.java
- src/main/java/dev/book/global/config/security/filter/JwtAuthenticationFilter.java
- src/main/resources/application-jwt.yaml
Swagger 반환 오류 해결
허용된 url을 yml 파일에서 관리, jwtFilter를 스킵하도록 설정
close #20
> [fix] 허용된 url을 yml 파일로 관리, jwtFilter 스킵 #20

- src/main/java/dev/book/challenge/api/ChallengeApi.java
- src/main/java/dev/book/challenge/api/ChallengeInviteApi.java
- src/main/java/dev/book/challenge/controller/ChallengeController.java
- src/main/java/dev/book/challenge/controller/ChallengeInviteController.java
- src/main/java/dev/book/challenge/dto/request/ChallengeCreateRequest.java
- src/main/java/dev/book/challenge/dto/request/ChallengeInviteRequest.java
- src/main/java/dev/book/challenge/dto/request/ChallengeUpdateRequest.java
- src/main/java/dev/book/challenge/dto/response/ErrorResponse.java
- src/main/java/dev/book/challenge/exception/ChallengeExceptionHandler.java
Swagger를 통한 챌린지 관련 API 명세서 작성입니다
Resolves #18 
어떤 변경 사항이 있나요?
API 문서 작업입니다.
> [Docs] Swagger를 통한 챌린지 관련 API 명세서 작성

- src/main/java/dev/book/global/config/security/util/CookieUtil.java
- src/main/resources/application-swagger.yaml
http 상태에서의 쿠키는 Secure false로 설정
서버 IP 환경변수 처리
#27 
어떤 변경 사항이 있나요?
> 27 bug 서버 쿠키 이슈

- src/main/java/dev/book/global/config/security/SecurityConfig.java
- src/main/java/dev/book/user/entity/UserEntity.java
- src/main/java/dev/book/user/exception/UserErrorCode.java
- src/main/java/dev/book/user_friend/controller/UserFriendController.java
- src/main/java/dev/book/user_friend/controller/UserFriendSwaggerController.java
- src/main/java/dev/book/user_friend/dto/response/FriendDetailResponseDto.java
- src/main/java/dev/book/user_friend/dto/response/FriendListResponseDto.java
- src/main/java/dev/book/user_friend/dto/response/FriendRequestListResponseDto.java
- src/main/java/dev/book/user_friend/dto/response/KakaoResponseDto.java
- src/main/java/dev/book/user_friend/dto/response/RequestFriendListResponseDto.java
- src/main/java/dev/book/user_friend/entity/UserFriend.java
- src/main/java/dev/book/user_friend/exception/UserFriendErrorCode.java
- src/main/java/dev/book/user_friend/exception/UserFriendException.java
- src/main/java/dev/book/user_friend/exception/UserFriendExceptionHandler.java
- src/main/java/dev/book/user_friend/repository/UserFriendRepository.java
- src/main/java/dev/book/user_friend/service/UserFriendService.java
- src/test/java/dev/book/user_friend/controller/UserFriendControllerTest.java
친구 관련 API 를 제작하였습니다.
1. 친구 요청 리스트 반환
2. 친구 요청 승낙
3. 친구 요청 거절
1. 친구 리스트 반환,
2. 친구 삭제
* 테스트 코드 작성
`친구 요청`과 `친구 맺음` .. 이런 친구 관계를 한 테이블 안에서 진행하려다 보니까 조금 헷갈리는 로직이 나왔네요 ㅜㅜ
column 중 friend_id 를 `친구 요청 받는 사람` 으로 생각해주시면 될 거 같습니다!
test1이 test2에게 친구 요청을 하면 
user = test1
friend = test2
test2가 친구 요청 내역들을 가져오려면 본인을 friend로 놓고 봐야합니다!
혹시 더 좋은 변수명이 있다면 적어주세요 .... /🥲
#9 
어떤 변경 사항이 있나요?
> 9 feature 친구 rud 기능 추가, 테스트 코드 추가

- src/main/java/dev/book/accountbook/controller/AccountBookController.java
- src/main/java/dev/book/accountbook/controller/BudgetController.java
- src/main/java/dev/book/accountbook/controller/StatController.java
- src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
- src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
- src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
- src/main/java/dev/book/accountbook/entity/AccountBook.java
- src/main/java/dev/book/accountbook/entity/Budget.java
- src/main/java/dev/book/accountbook/entity/BudgetAccountBook.java
- src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
- src/main/java/dev/book/accountbook/service/BudgetService.java
- src/main/java/dev/book/accountbook/service/StatService.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
- src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
- src/test/java/dev/book/global/config/security/controller/AuthControllerTest.java
수입 / 지출 유닛, 통합 테스트 작성
통계 유닛, 통합 테스트 작성
Resolves: #29
테스트 코드 작성
> 29 test 가계부 및 통계 테스트 코드 작성

- src/main/java/dev/book/accountbook/type/Category.java
- src/main/java/dev/book/accountbook/type/Frequency.java
controller에서 request를 받을 때 들어오는 소문자가 대문자로 변환이 안되어 bad request 가 뜨는 문제가 있었습니다.
Resolves: #36 
어떤 변경 사항이 있나요?
- enum 소문자에서 대문자 변환이 가능하도록 수정했습니다.
> [fix] enum 대소문자 변환 로직 추가

- src/test/java/dev/book/challenge/controller/ChallengeControllerTest.java
- src/test/java/dev/book/challenge/controller/ChallengeInviteControllerTest.java
챌린지 관련 컨트롤러 단위 테스트를 작성 하였습니다
Resolves: #33 
어떤 변경 사항이 있나요?
- 챌린지 생성,조회,수정,삭제,참여,초대,수락,거절에 대한 해피 케이스에 대한 단위 테스트를 작성하였습니다
- 추후 예외 케이스에 더 작성 하도록 하겠습니다.
> [Test] 챌린지 관련 컨트롤러 단위테스트 작성

- src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
- src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookIncomeRequest.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookSpendRequest.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeResponse.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookSpendResponse.java
- src/main/java/dev/book/accountbook/entity/AccountBook.java
- src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
- src/main/java/dev/book/accountbook/repository/BudgetRepositoryImpl.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
- src/main/java/dev/book/accountbook/service/BudgetService.java
- src/main/java/dev/book/accountbook/service/CodefService.java
- src/main/java/dev/book/accountbook/service/StatService.java
- src/main/java/dev/book/accountbook/type/Frequency.java
지출 / 수입 등록 시 시간 직접 입력도 가능하도록 변경하였습니다.
Resolves: #49
> 49 refactor 지출 수입 수동 등록 시 시간을 직접 입력할 수 있게 변경

- src/main/java/dev/book/accountbook/controller/AccountBookController.java
- src/main/java/dev/book/accountbook/controller/BudgetController.java
- src/main/java/dev/book/accountbook/controller/CodefController.java
- src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
- src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookIncomeRequest.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookListRequest.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookMonthRequest.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookRequest.java
- src/main/java/dev/book/accountbook/dto/request/AccountBookSpendRequest.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeResponse.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookMonthResponse.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookPeriodResponse.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookSpendResponse.java
- src/main/java/dev/book/accountbook/dto/response/BudgetResponse.java
- src/main/java/dev/book/accountbook/entity/AccountBook.java
- src/main/java/dev/book/accountbook/exception/accountbook/AccountBookErrorCode.java
- src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
- src/main/java/dev/book/accountbook/repository/BudgetRepository.java
- src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryCustom.java
- src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryImpl.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
- src/main/java/dev/book/accountbook/service/BudgetService.java
- src/main/java/dev/book/accountbook/service/StatService.java
- src/test/java/dev/book/accountbook/controller/AccountBookControllerTest.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
- src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
캘린더를 위한 api 추가
Resolves: #55 
어떤 변경 사항이 있나요?
> 55 feature 캘린더를 위한 api 추가

- .github/workflows/deploy.yml
수동 -> 깃허브액션을 통한 자동 배포 구축
기존 빌드된 jar 파일 삭제 후 배포 할수 있게 수정하였습니다
Resolves : #63 
어떤 변경 사항이 있나요?
수동 -> 깃허브액션을 통한 자동 배포 구축
> [CI] CI/CD 구축

- src/main/java/dev/book/accountbook/entity/Budget.java
- src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
- src/main/java/dev/book/accountbook/repository/BudgetRepository.java
- src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryCustom.java
- src/main/java/dev/book/accountbook/repository/querydsl/BudgetRepositoryImpl.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
- src/main/java/dev/book/accountbook/service/StatService.java
- src/main/java/dev/book/accountbook/type/BudgetLimit.java
- src/main/java/dev/book/accountbook/type/Frequency.java
- src/main/java/dev/book/accountbook/type/PeriodRange.java
- src/main/java/dev/book/global/config/Firebase/FcmController.java
- src/main/java/dev/book/global/config/Firebase/service/FCMService.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
- src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
> 61 feat 예산 대비 과소비 알림 추가

- src/main/java/dev/book/accountbook/controller/BudgetController.java
- src/main/java/dev/book/accountbook/repository/BudgetRepository.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
- src/main/java/dev/book/accountbook/service/BudgetService.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/BudgetServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/BudgetServiceUnitTest.java
- src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
예산 서비스 테스트 코드입니다.
Resolves: #70
> 70 test budget 서비스 테스트 작성

- src/main/java/dev/book/achievement/service/AchievementService.java
- src/main/java/dev/book/challenge/controller/ChallengeController.java
- src/main/java/dev/book/challenge/controller/ChallengeInviteController.java
- src/main/java/dev/book/challenge/controller/swagger/ChallengeApi.java
- src/main/java/dev/book/challenge/controller/swagger/ChallengeInviteApi.java
- src/main/java/dev/book/global/config/security/controller/AuthController.java
- src/main/java/dev/book/global/config/security/controller/swagger/AuthApi.java
- src/main/java/dev/book/global/sse/controller/SseController.java
- src/main/java/dev/book/global/sse/controller/swagger/SseApi.java
- src/main/java/dev/book/global/sse/dto/SseResponse.java
- src/main/java/dev/book/global/sse/repository/SseEmitterRepository.java
- src/main/java/dev/book/global/sse/repository/SseEmitterRepositoryImpl.java
- src/main/java/dev/book/global/sse/service/SseService.java
- src/main/java/dev/book/global/sse/type/SseType.java
- src/main/java/dev/book/user/controller/UserController.java
- src/main/java/dev/book/user/controller/swagger/UserApi.java
- src/main/java/dev/book/user/user_friend/controller/UserFriendController.java
- src/main/java/dev/book/user/user_friend/controller/swagger/UserFriendApi.java
- src/test/java/dev/book/global/sse/service/SseServiceTest.java
업적 달성 시 클라이언트 측에 알림을 보내기 위해 SSE 방식을 선택하였습니다.
#67 
어떤 변경 사항이 있나요?
> 67 feature sse 설정 추가

- src/main/java/dev/book/achievement/service/AchievementService.java
- src/main/java/dev/book/challenge/dto/response/ChallengeParticipantResponse.java
- src/main/java/dev/book/challenge/scheduler/ChallengeScheduler.java
- src/main/java/dev/book/challenge/service/ChallengeService.java
- src/main/java/dev/book/challenge/user_challenge/entity/UserChallenge.java
- src/main/java/dev/book/challenge/user_challenge/repository/UserChallengeRepository.java
- src/main/java/dev/book/global/sse/bean/EmitterStorage.java
- src/main/java/dev/book/global/sse/controller/SseController.java
- src/main/java/dev/book/global/sse/controller/swagger/SseApi.java
- src/main/java/dev/book/global/sse/dto/SseAchievementResponse.java
- src/main/java/dev/book/global/sse/dto/SseResponse.java
- src/main/java/dev/book/global/sse/dto/response/SseAchievementResponse.java
- src/main/java/dev/book/global/sse/dto/response/SseTipResponse.java
- src/main/java/dev/book/global/sse/repository/EmitterStorage.java
- src/main/java/dev/book/global/sse/repository/SseEmitterRepository.java
- src/main/java/dev/book/global/sse/repository/SseEmitterRepositoryImpl.java
- src/main/java/dev/book/global/sse/service/SseService.java
- src/main/java/dev/book/global/sse/type/SseType.java
- src/main/java/dev/book/tip/controller/TipController.java
- src/main/java/dev/book/tip/controller/swagger/TipApi.java
- src/main/java/dev/book/tip/dto/request/TipRequest.java
- src/main/java/dev/book/tip/dto/response/TipResponse.java
- src/main/java/dev/book/tip/entity/Tip.java
- src/main/java/dev/book/tip/exception/TipErrorCode.java
- src/main/java/dev/book/tip/exception/TipErrorException.java
- src/main/java/dev/book/tip/repository/TipRepository.java
- src/main/java/dev/book/tip/service/TipService.java
- src/test/java/dev/book/global/sse/service/SseServiceTest.java
TIP 작성 시 브로드캐스팅으로 모든 유저에게 작성된 TIP을 반환합니다.
TIP 작성은 성공한 챌린지 당 하나만 작성할 수 있기에 user_challenge 부분에 isWriteTip 칼럼을 추가하였습니다.
스케줄러로 챌린지의 성공 여부 판단을 진행하여 나의 챌린지 조회 때 칼럼만 반환하도록 수정하였습니다.
나의 챌린지 반환 시 tip 작성 여부도 추가하여 반환하였습니다.
#66 
어떤 변경 사항이 있나요?
SSE 로직을 이벤트 Listener로 빼는 게 좋을까요?
혹시 로직이 변경될 수도 있어서 승인 후에 테스트 코드 작성하도록 하겠습니다!
> 66 feature tip 기능 추가

- src/main/java/dev/book/global/config/security/interceptor/JwtWebsocketInterceptor.java
- src/main/java/dev/book/global/config/websocket/WebSocketConfig.java
처음에 ChannelInterceptor를 활용하여 구현할려고 하였지만 
StompHeaderAccessor는 Stomp 프레임에 포함된 헤더만 접근이 가능하다고하였습니다
쿠키는 최초 Http 연결 시만 포함되기때문에 Channelinterceptor에는 접근을 하지 못해 못가져오는 문제가 발생 
HandshakeInterceptor(Http 최초 요청을 가로 가지는 인터페이스 를 구현하였습니다.
Resolve #74 
어떤 변경 사항이 있나요?
> [Feat] 웹 소켓 인터셉터 구현

- src/main/java/dev/book/accountbook/controller/StatController.java
- src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
- src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
- src/main/java/dev/book/accountbook/repository/TempAccountBookRepository.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
> 85 fix 요청 중복

- src/main/java/dev/book/global/config/security/util/CookieUtil.java
- src/main/resources/application-jwt.yaml
쿠키 도메인 설정과 access_token 만료 시간을 수정하였습니다.
#92 
어떤 변경 사항이 있나요?
> [fix] 쿠키 설정 수정 및 access_token 만료 시간 수정 #92

- src/main/java/dev/book/global/config/security/util/CookieUtil.java
> [fix] 쿠키 도메인 설정 변경 #92

- src/main/java/dev/book/global/config/security/util/CookieUtil.java
> [fix] 쿠키 도메인 localhost 설정 제외 #92

- src/main/java/dev/book/accountbook/controller/AccountBookController.java
- src/main/java/dev/book/accountbook/controller/BudgetController.java
- src/main/java/dev/book/accountbook/controller/StatController.java
- src/main/java/dev/book/accountbook/controller/swagger/AccountBookApi.java
- src/main/java/dev/book/accountbook/controller/swagger/BudgetApi.java
- src/main/java/dev/book/accountbook/controller/swagger/StatApi.java
- src/main/java/dev/book/accountbook/dto/request/BudgetFindRequest.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookIncomeListResponse.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookPeriodListResponse.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookPeriodResponse.java
- src/main/java/dev/book/accountbook/dto/response/AccountBookSpendListResponse.java
- src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
- src/main/java/dev/book/accountbook/repository/BudgetRepository.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
- src/main/java/dev/book/accountbook/service/BudgetService.java
- src/main/java/dev/book/accountbook/service/StatService.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/AccountBookServiceUnitTest.java
- src/test/java/dev/book/accountbook/service/BudgetServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/BudgetServiceUnitTest.java
- src/test/java/dev/book/accountbook/service/StatServiceIntegrationTest.java
- src/test/java/dev/book/accountbook/service/StatServiceUnitTest.java
일부 API에 페이징을 추가했습니다.
Resolves: #89
> 89 feature 페이징 추가

- src/main/java/dev/book/user/entity/UserEntity.java
- src/main/java/dev/book/user/service/UserService.java
- src/main/resources/application-jwt.yaml
카테고리 변경 로직 수정
엑세스 토큰 30분으로 복귀
docs 설정
#103 
어떤 변경 사항이 있나요?
> [refactor] 카테고리 변경 로직에서 불필요한 쿼리 삭제

- src/main/java/dev/book/accountbook/repository/AccountBookRepository.java
- src/main/java/dev/book/accountbook/repository/TempAccountBookRepository.java
- src/main/java/dev/book/accountbook/service/AccountBookService.java
트랜잭션 readOnly 추가
Resolves: #105
> 105 refactor 코드 최적화

- src/main/java/dev/book/challenge/rank/service/RankService.java
- src/main/java/dev/book/challenge/scheduler/ChallengeScheduler.java
- src/main/java/dev/book/challenge/service/ChallengeInviteService.java
- src/main/java/dev/book/challenge/service/ChallengeLockService.java
- src/main/java/dev/book/challenge/service/ChallengeService.java
로그 작성 및 읽는 작업에는 readonly true 설정 
#106 
어떤 변경 사항이 있나요?
> Fix/#106 코드 피드백 반영
